### ISSUE TITLE
Decorfloor - Missing County for two jobs on peviitor.ro

### ISSUE THREAD

**Issue by AdrianaCionca** [peviitor-ro/search-engine#441]
ENVIRONMENT: production
URL: https://peviitor.ro
Browser: Microsoft Edge
Device: Laptop
OS: Windows 10

STEPS TO REPRODUCE:

1. Open the URL in the browser
2. Search for "Decorfloor" Company
5. Check the County of the jobs

EXPECTED RESULTS:
All jobs have a city and county as location

ACTUAL RESULTS:
For two jobs the county is missing on peviitor.ro:
- Project Manager
- Financial Team Assistant

On the solr.peviitor.ro the County is displayed

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/0e118e4d-762a-4fe4-9845-05327ddc5c69)

![image](https://github.com/peviitor-ro/scrapers.js/assets/122023703/3b12c908-def7-48b9-a112-10f745285d2e)

**Comment by robert-burcea** [comment]
Yep, it doesn't show the county but momentarily this is by design because if the job has several locations with several cities and counties the job card gets too crowded so temporarily it only shows the job cities if the job has > 1 location, and city+county if it has 1 location. I will contact Patricia for an elegant UI solution for this.

**Comment by CalinCatuta** [comment]
County nu va mai fi aratat in UI.
